#cloud-config
users:
  - default
system_info:
  distro: ubuntu # <or other distr>
  default_user:
    name: # <UserName>
    gecos: # <FullUserName>
    passwd: # <hash password via mkpasswd>
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }
    groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
timezone: Europe/Moscow
package_update: true
package_upgrade: true
packages:
  - figlet
write_files:
  - path: /etc/update-motd.d/99-custom
    content: |
      #!/bin/bash
      echo "$HOSTNAME" | figlet -k
    permissions: '0755'
  - path: /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
    content: |
      PasswordAuthentication yes
    permissions: '0644'
runcmd:
  - truncate -s 0 /etc/machine-id
  - cloud-init clean --logs
power_state:
  delay: 1
  mode: poweroff
